spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 2000
        response-timeout: 2s
      routes:
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**,/api/products/**,/api/config/**,/api/traffic/**
          filters:
            - name: CircuitBreaker
              args:
                name: authGatewayCircuitBreaker
                fallbackUri: forward:/fallback/auth
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 8
                redis-rate-limiter.burstCapacity: 12
                redis-rate-limiter.requestedTokens: 1
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/seckill/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderGatewayCircuitBreaker
                fallbackUri: forward:/fallback/order
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
        - id: inventory-service-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventoryGatewayCircuitBreaker
                fallbackUri: forward:/fallback/inventory
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 3000ms

server:
  port: 9093
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: info
