spring.application.name=gateway-service
spring.config.import=optional:nacos:${spring.application.name}.yaml

spring.cloud.nacos.server-addr=${NACOS_SERVER_ADDR:nacos:8848}
spring.cloud.nacos.discovery.server-addr=${spring.cloud.nacos.server-addr}
spring.cloud.nacos.config.server-addr=${spring.cloud.nacos.server-addr}
spring.cloud.nacos.config.file-extension=yaml
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.cloud.nacos.config.refresh-enabled=true

server.port=9093
server.address=0.0.0.0

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always
