-- 创建用户表
CREATE TABLE IF NOT EXISTS `users` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户唯一ID',
    `username` VARCHAR(50) NOT NULL COMMENT '用户名',
    `phone_number` VARCHAR(20) UNIQUE NOT NULL COMMENT '手机号（唯一）',
    `password_hash` VARCHAR(255) NOT NULL COMMENT '密码哈希值',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '信息更新时间',
    `last_login` TIMESTAMP NULL DEFAULT NULL COMMENT '最近登录时间',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '用户状态: 0=禁用,1=启用',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';